name: Build an push to AWS

on:
    push:
        branches:
            - "*"


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '6.0'

            - name: Build projckt
              run: dotnet restore; dotnet publish -o site;

            - name: create zip package
              run: cd site; zip ../site.zip *;

            - name: Deploy toaws EB
              uses: einaregilsson/beanstalk-deploy@v21
              with: 
                aws_access_key: ${{ secret_aws_key }}
                aws_secret_key: ${{ secret_access_key }}
                application_name: webapi
                environment_name: webapi-env
                version_label: ${{ github.run_id}}
                region: eu-north-1
                deployment_package: site.zip